name: Deploy

on:
  # Triggers the workflow on push to master branch. 
  # But ignore a change erduced to the README.
  push:
    branches: [ master ]
    paths-ignore:
      - README.md

  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Validate
        uses: appleboy/ssh-action@master
        with:
          host: isclab.dcc.uchile.cl
          username: isclab
          port: 122
          key: ${{ secrets.ISCLAB_SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.ISCLAB_SSH_PASSPHRASE }}
          script: whoami
